### ISSUE TITLE
create_batch.sh writes relative path to EXOME_TARGET in target_regions.txt. Should be absolute path

### ISSUE THREAD

**Issue by hdashnow** [MelbourneGenomics/cpipe#11]
There are really two issues here:
- [ ] Add bed file naming convention to README in cpipe/designs/
- [ ] Change create_batch.sh so it creates a relative path to EXOME_TARGET

When I went to create a batch, I did this:

``` bash
$ ./pipeline/scripts/create_batch.sh test_batch CARDIOM NEXTERA12

=================== Cpipe Batch Creation Helper Script ========================


========================== ERROR ==============================
No file called NEXTERA12 could be found. You may need to specify this file
with an absolute path
===============================================================
```

This was surprising because I had the file cpipe/designs/NEXTERA12/target_region.bed

So I did this:

```
$ ./pipeline/scripts/create_batch.sh test_batch CARDIOM designs/NEXTERA12/target_region.bed 
```

The pipeline seemed to be running fine until # Stage summary_pdf:

```
Caught: java.io.FileNotFoundException: designs/NEXTERA12/target_region.bed (No such file or directory)
java.io.FileNotFoundException: designs/NEXTERA12/target_region.bed (No such file or directory)
```

It turns out EXOME_TARGET is set to the path I gave to create_batch.sh, which was relative to the cpipe home directory, not the analysis directory.

```
[hdashnow@merri NA12878]$ cat target_regions.txt 

DISEASE_COHORTS="CARDIOM"
EXOME_TARGET="designs/NEXTERA12/target_region.bed"
```

So, create_batch.sh should use $BASE to set the absolute path of EXOME_TARGET in target_regions.txt.

**Comment by ssadedin** [comment]
Fixed in 65aa0d4afdc1d14a288270aba81fc0d9a654fa7b and 7fbecdc
